export enum InventoryType {
    ASSAULT_RIFLE,
    SNIPER_RIFLE,
    SHOTGUN,
    HEAVY_PISTOL,
    SUB_MACHINE_GUN,
    TEST,
    ARMOR_EQUIP,
    WEAPON_EQUIP,
    CONSUMABLE_STOCK,
    AMMO_EQUIP,
    CHARACTER,
    CONSUMABLE_CAPACITY,
    CONSUMABLE_OTHER,
    UNITS,
    GEAR_EQUIP,
    FLAG,
    UNKNOWN
}

export interface InventoryDefinition {
    name: string;
    type: InventoryType;
}


/**
 * A Mapping defining the names and types of the different inventory slots
 */
export const InventoryDefinitions: Record<number, InventoryDefinition> = {
    0: { name: "M-8 Avenger", type: InventoryType.ASSAULT_RIFLE },
    1: { name: "Collector Rifle", type: InventoryType.ASSAULT_RIFLE },
    2: { name: "Geth Pulse Rifle", type: InventoryType.ASSAULT_RIFLE },
    3: { name: "M-96 Mattock", type: InventoryType.ASSAULT_RIFLE },
    4: { name: "Phaeston", type: InventoryType.ASSAULT_RIFLE },
    5: { name: "M-37 Falcon", type: InventoryType.ASSAULT_RIFLE },
    6: { name: "M-76 Revenant", type: InventoryType.ASSAULT_RIFLE },
    7: { name: "M-15 Vindicator", type: InventoryType.ASSAULT_RIFLE },
    8: { name: "M-29 Incisor", type: InventoryType.SNIPER_RIFLE },
    9: { name: "M-92 Mantis", type: InventoryType.SNIPER_RIFLE },
    10: { name: "M-13 Raptor", type: InventoryType.SNIPER_RIFLE },
    11: { name: "Javelin", type: InventoryType.SNIPER_RIFLE },
    12: { name: "M-97 Viper", type: InventoryType.SNIPER_RIFLE },
    13: { name: "M-98 Widow", type: InventoryType.SNIPER_RIFLE },
    14: { name: "M-300 Claymore", type: InventoryType.SHOTGUN },
    15: { name: "M-22 Eviscerator", type: InventoryType.SHOTGUN },
    16: { name: "Geth Plasma Shotgun", type: InventoryType.SHOTGUN },
    17: { name: "M-23 Katana", type: InventoryType.SHOTGUN },
    18: { name: "Graal Spike Thrower", type: InventoryType.SHOTGUN },
    19: { name: "Disciple", type: InventoryType.SHOTGUN },
    20: { name: "M-27 Scimitar", type: InventoryType.SHOTGUN },
    21: { name: "M-6 Carnifex", type: InventoryType.HEAVY_PISTOL },
    22: { name: "M-358 Talon", type: InventoryType.HEAVY_PISTOL },
    23: { name: "Arc Pistol", type: InventoryType.HEAVY_PISTOL },
    24: { name: "M-5 Phalanx", type: InventoryType.HEAVY_PISTOL },
    25: { name: "M-3 Predator", type: InventoryType.HEAVY_PISTOL },
    26: { name: "Scorpion", type: InventoryType.HEAVY_PISTOL },
    27: { name: "M-12 Locust", type: InventoryType.SUB_MACHINE_GUN },
    28: { name: "M-25 Hornet", type: InventoryType.SUB_MACHINE_GUN },
    29: { name: "M-4 Shuriken", type: InventoryType.SUB_MACHINE_GUN },
    30: { name: "M-9 Tempest", type: InventoryType.SUB_MACHINE_GUN },
    // 31..55
    56: { name: "MPAssaultRifles_InventoryLocked", type: InventoryType.TEST },
    57: { name: "MPPistols_InventoryLocked", type: InventoryType.TEST },
    58: { name: "MPShotguns_InventoryLocked", type: InventoryType.TEST },
    59: { name: "MPSMGs_InventoryLocked", type: InventoryType.TEST },
    60: { name: "MPSniperRifles_InventoryLocked", type: InventoryType.TEST },
    // 61..72
    73: { name: "Stabilization Module 1", type: InventoryType.ARMOR_EQUIP },
    74: { name: "Stabilization Module 2", type: InventoryType.ARMOR_EQUIP },
    75: { name: "Stabilization Module 3", type: InventoryType.ARMOR_EQUIP },
    76: { name: "Shield Power Cells 1", type: InventoryType.ARMOR_EQUIP },
    77: { name: "Shield Power Cells 2", type: InventoryType.ARMOR_EQUIP },
    78: { name: "Shield Power Cells 3", type: InventoryType.ARMOR_EQUIP },
    79: { name: "Strength Enhancer 1", type: InventoryType.WEAPON_EQUIP },
    80: { name: "Strength Enhancer 2", type: InventoryType.WEAPON_EQUIP },
    81: { name: "Strength Enhancer 3", type: InventoryType.WEAPON_EQUIP },
    82: { name: "Targeting VI 1", type: InventoryType.WEAPON_EQUIP },
    83: { name: "Targeting VI 2", type: InventoryType.WEAPON_EQUIP },
    84: { name: "Targeting VI 3", type: InventoryType.WEAPON_EQUIP },
    86: { name: "Thermal Clip Pack", type: InventoryType.CONSUMABLE_STOCK },
    87: { name: "Medi-Gel", type: InventoryType.CONSUMABLE_STOCK },
    88: { name: "Cobra Missile Launcher", type: InventoryType.CONSUMABLE_STOCK },
    89: { name: "Ops Survival Pack", type: InventoryType.CONSUMABLE_STOCK },
    90: { name: "Incendiary Rounds 1", type: InventoryType.AMMO_EQUIP },
    91: { name: "incendiary Rounds 2", type: InventoryType.AMMO_EQUIP },
    92: { name: "Incendiary Rounds 3", type: InventoryType.AMMO_EQUIP },
    93: { name: "Disruptor Rounds 1", type: InventoryType.AMMO_EQUIP },
    94: { name: "Disruptor Rounds 2", type: InventoryType.AMMO_EQUIP },
    95: { name: "Disruptor Rounds 3", type: InventoryType.AMMO_EQUIP },
    96: { name: "Armor Piercing 1", type: InventoryType.AMMO_EQUIP },
    97: { name: "Armor Piercing 2", type: InventoryType.AMMO_EQUIP },
    98: { name: "Armor Piercing 3", type: InventoryType.AMMO_EQUIP },
    99: { name: "Warp Rounds 1", type: InventoryType.AMMO_EQUIP },
    100: { name: "Warp Rounds 2", type: InventoryType.AMMO_EQUIP },
    101: { name: "Warp Rounds 3", type: InventoryType.AMMO_EQUIP },
    102: { name: "Cryo Rounds 1", type: InventoryType.AMMO_EQUIP },
    103: { name: "Cyro Rounds 2", type: InventoryType.AMMO_EQUIP },
    104: { name: "Cryo Rounds 3", type: InventoryType.AMMO_EQUIP },
    105: { name: "Power Efficiency Module 1", type: InventoryType.ARMOR_EQUIP },
    106: { name: "Power Efficiency Module 2", type: InventoryType.ARMOR_EQUIP },
    107: { name: "Power Efficiency Module 3", type: InventoryType.ARMOR_EQUIP },
    // 108..109
    110: { name: "N7 Valiant", type: InventoryType.SNIPER_RIFLE },
    111: { name: "Assault Rifle Rail Amp 1", type: InventoryType.WEAPON_EQUIP },
    112: { name: "Assault Rifle Rail Amp 2", type: InventoryType.WEAPON_EQUIP },
    113: { name: "Assault Rifle Rail Amp 3", type: InventoryType.WEAPON_EQUIP },
    114: { name: "Sniper Rifle Rail Amp 1", type: InventoryType.WEAPON_EQUIP },
    115: { name: "Sniper Rifle Rail Amp 2", type: InventoryType.WEAPON_EQUIP },
    116: { name: "Sniper Rifle Rail Amp 3", type: InventoryType.WEAPON_EQUIP },
    117: { name: "Shotgun Rail Amp 1", type: InventoryType.WEAPON_EQUIP },
    118: { name: "Shotgun Rail Amp 2", type: InventoryType.WEAPON_EQUIP },
    119: { name: "Shotgun Rail Amp 3", type: InventoryType.WEAPON_EQUIP },
    120: { name: "Pistol Rail Amp 1", type: InventoryType.WEAPON_EQUIP },
    121: { name: "Pistol Rail Amp 2", type: InventoryType.WEAPON_EQUIP },
    122: { name: "Pistol Rail Amp 3", type: InventoryType.WEAPON_EQUIP },
    123: { name: "SMG Rail Amp 1", type: InventoryType.WEAPON_EQUIP },
    124: { name: "SMG Rail Amp 2", type: InventoryType.WEAPON_EQUIP },
    125: { name: "SMG Rail Amp 3", type: InventoryType.WEAPON_EQUIP },
    126: { name: "Adrenaline Module 1", type: InventoryType.ARMOR_EQUIP },
    127: { name: "Adrenaline Module 2", type: InventoryType.ARMOR_EQUIP },
    128: { name: "Adrenaline Module 3", type: InventoryType.ARMOR_EQUIP },
    129: { name: "Cyclonic Modulator 1", type: InventoryType.ARMOR_EQUIP },
    130: { name: "Cyclonic Modulator 2", type: InventoryType.ARMOR_EQUIP },
    131: { name: "Cyclonic Modulator 3", type: InventoryType.ARMOR_EQUIP },
    132: { name: "ActiveXPBonusMultiplierIndex_1", type: InventoryType.TEST },
    133: { name: "ActiveXPBonusMultiplierIndex_2", type: InventoryType.TEST },
    134: { name: "ActiveXPBonusMultiplierIndex_3", type: InventoryType.TEST },
    135: { name: "M-99 Saber", type: InventoryType.ASSAULT_RIFLE },
    136: { name: "Black Widow", type: InventoryType.SNIPER_RIFLE },
    137: { name: "M-11 Wraith", type: InventoryType.SHOTGUN },
    138: { name: "M-77 Paladin", type: InventoryType.HEAVY_PISTOL },
    // 139..216
    217: { name: "Asari Adept", type: InventoryType.CHARACTER },
    218: { name: "Drell Adept", type: InventoryType.CHARACTER },
    219: { name: "Quarian Engineer", type: InventoryType.CHARACTER },
    220: { name: "Salarian Engineer", type: InventoryType.CHARACTER },
    221: { name: "Salarian Infiltrator", type: InventoryType.CHARACTER },
    222: { name: "Quarian Infiltrator", type: InventoryType.CHARACTER },
    223: { name: "Turian Sentinel", type: InventoryType.CHARACTER },
    224: { name: "Krogan Sentinel", type: InventoryType.CHARACTER },
    225: { name: "Krogan Soldier", type: InventoryType.CHARACTER },
    226: { name: "Turian Soldier", type: InventoryType.CHARACTER },
    227: { name: "Drell Vanguard", type: InventoryType.CHARACTER },
    228: { name: "Asari Vanguard", type: InventoryType.CHARACTER },
    // 229..237
    238: { name: "Geth Engineer", type: InventoryType.CHARACTER },
    239: { name: "Geth Infiltrator", type: InventoryType.CHARACTER },
    240: { name: "Batarian Soldier", type: InventoryType.CHARACTER },
    241: { name: "Chakram Launcher (unused)", type: InventoryType.ASSAULT_RIFLE },
    242: { name: "Themal Clip Pack", type: InventoryType.CONSUMABLE_CAPACITY },
    243: { name: "Medi-Gel", type: InventoryType.CONSUMABLE_CAPACITY },
    244: { name: "Cobra Missile Launcher", type: InventoryType.CONSUMABLE_CAPACITY },
    245: { name: "Ops Survival Pack", type: InventoryType.CONSUMABLE_CAPACITY },
    246: { name: "Reset Powers", type: InventoryType.UNITS },
    247: { name: "Human Female Adept", type: InventoryType.CHARACTER },
    248: { name: "Human Male Adept", type: InventoryType.CHARACTER },
    249: { name: "Human Female Engineer", type: InventoryType.CHARACTER },
    250: { name: "Human Male Engineer", type: InventoryType.CHARACTER },
    251: { name: "Human Female Infiltrator", type: InventoryType.CHARACTER },
    252: { name: "Human Male Infiltrator", type: InventoryType.CHARACTER },
    253: { name: "Human Female Sentinel", type: InventoryType.CHARACTER },
    254: { name: "Human Male Sentinel", type: InventoryType.CHARACTER },
    255: { name: "Human Female Soldier", type: InventoryType.CHARACTER },
    256: { name: "Human Male Soldier", type: InventoryType.CHARACTER },
    257: { name: "Human Female Vanguard", type: InventoryType.CHARACTER },
    258: { name: "Human Male Vanguard", type: InventoryType.CHARACTER },
    259: { name: "Power Amplifier Module 1", type: InventoryType.ARMOR_EQUIP },
    260: { name: "Power Amplifier Module 2", type: InventoryType.ARMOR_EQUIP },
    261: { name: "Power Amplifier Module 3", type: InventoryType.ARMOR_EQUIP },
    262: { name: "N7 Crusader", type: InventoryType.SHOTGUN },
    263: { name: "N7 Eagle", type: InventoryType.HEAVY_PISTOL },
    264: { name: "N7 Hurricane", type: InventoryType.SUB_MACHINE_GUN },
    // 265..266
    267: { name: "Batarian Sentinel", type: InventoryType.CHARACTER },
    268: { name: "Battlefield 3 Soldier", type: InventoryType.CHARACTER },
    270: { name: "Welcome screen", type: InventoryType.FLAG },
    272: { name: "Krogan Vanguard", type: InventoryType.CHARACTER },
    273: { name: "Asari Justicar Adept", type: InventoryType.CHARACTER },
    274: { name: "Striker Assault Rifle", type: InventoryType.ASSAULT_RIFLE },
    275: { name: "Kishock Harpoon Gun", type: InventoryType.SNIPER_RIFLE },
    276: { name: "Geth Plasma SMG", type: InventoryType.SUB_MACHINE_GUN },
    278: { name: "Vorcha Soldier", type: InventoryType.CHARACTER },
    279: { name: "Vorcha Sentinel", type: InventoryType.CHARACTER },
    280: { name: "Quarian Male Engineer", type: InventoryType.CHARACTER },
    281: { name: "Quarian Male Infiltrator", type: InventoryType.CHARACTER },
    282: { name: "Phoenix Adept", type: InventoryType.CHARACTER },
    283: { name: "Phoenix Vanguard", type: InventoryType.CHARACTER },
    // 284..285
    286: { name: "Cerberus Harrier", type: InventoryType.ASSAULT_RIFLE },
    287: { name: "Reegar Carbine", type: InventoryType.SHOTGUN },
    288: { name: "Krysae Sniper Rifle", type: InventoryType.SNIPER_RIFLE },
    // 289..329
    330: { name: "Hydraulic Joints", type: InventoryType.GEAR_EQUIP },
    331: { name: "Vulnerability VI", type: InventoryType.GEAR_EQUIP },
    332: { name: "Mental Focuser", type: InventoryType.GEAR_EQUIP },
    333: { name: "Structural Ergonomics", type: InventoryType.GEAR_EQUIP },
    334: { name: "Shield Booster", type: InventoryType.GEAR_EQUIP },
    335: { name: "Multicapacitor", type: InventoryType.GEAR_EQUIP },
    // 336
    337: { name: "Assault Rifle Amp", type: InventoryType.GEAR_EQUIP },
    338: { name: "Sniper Rifle Amp", type: InventoryType.GEAR_EQUIP },
    339: { name: "Shotgun Amp", type: InventoryType.GEAR_EQUIP },
    340: { name: "Pistol Amp", type: InventoryType.GEAR_EQUIP },
    341: { name: "SMG Amp", type: InventoryType.GEAR_EQUIP },
    // 342
    343: { name: "Grenade Capacity", type: InventoryType.GEAR_EQUIP },
    344: { name: "Warfighter Package", type: InventoryType.GEAR_EQUIP },
    345: { name: "Commando Package", type: InventoryType.GEAR_EQUIP },
    346: { name: "Stronghold Package", type: InventoryType.GEAR_EQUIP },
    347: { name: "Berserker Package", type: InventoryType.GEAR_EQUIP },
    348: { name: "Expert Package", type: InventoryType.GEAR_EQUIP },
    349: { name: "Operative Package", type: InventoryType.GEAR_EQUIP },
    // 350..357
    358: { name: "Particle Rifle", type: InventoryType.ASSAULT_RIFLE },
    // 359..366
    367: { name: "M-55 Argus", type: InventoryType.ASSAULT_RIFLE },
    368: { name: "N7 Valkyrie", type: InventoryType.ASSAULT_RIFLE },
    369: { name: "M-90 Indra", type: InventoryType.SNIPER_RIFLE },
    370: { name: "AT-12 Raider", type: InventoryType.SHOTGUN },
    // 371..372
    373: { name: "N7 Fury Adept", type: InventoryType.CHARACTER },
    374: { name: "N7 Demolisher Engineer", type: InventoryType.CHARACTER },
    375: { name: "N7 Paladin Sentinel", type: InventoryType.CHARACTER },
    376: { name: "N7 Slayer Vanguard", type: InventoryType.CHARACTER },
    377: { name: "N7 Shadow Infiltrator", type: InventoryType.CHARACTER },
    378: { name: "N7 Destroyer Soldier", type: InventoryType.CHARACTER },
    // 379..405
    406: { name: "AssaultRifleSuperScope", type: InventoryType.WEAPON_EQUIP },
    407: { name: "PistolHeadShot", type: InventoryType.WEAPON_EQUIP },
    408: { name: "PistolSuperDamage", type: InventoryType.WEAPON_EQUIP },
    409: { name: "PistolUltraLight", type: InventoryType.WEAPON_EQUIP },
    410: { name: "ShotgunDamageAndPen", type: InventoryType.WEAPON_EQUIP },
    411: { name: "ShotgunSuperMelee", type: InventoryType.WEAPON_EQUIP },
    412: { name: "SMGPenetration", type: InventoryType.WEAPON_EQUIP },
    413: { name: "SMGStabilization", type: InventoryType.WEAPON_EQUIP },
    414: { name: "SniperRifleDamageAndPen", type: InventoryType.WEAPON_EQUIP },
    415: { name: "SniperRifleSuperScope", type: InventoryType.WEAPON_EQUIP },
    416: { name: "Combatives Upgrade", type: InventoryType.GEAR_EQUIP },
    417: { name: "Martial Biotic Amp", type: InventoryType.GEAR_EQUIP },
    418: { name: "Juggernaut Shield", type: InventoryType.GEAR_EQUIP },
    419: { name: "Shock Trooper Upgrade", type: InventoryType.GEAR_EQUIP },
    420: { name: "Guerrilla Upgrade", type: InventoryType.GEAR_EQUIP },
    421: { name: "Omni-Capacitors", type: InventoryType.GEAR_EQUIP },
    422: { name: "Barrage Upgrade", type: InventoryType.GEAR_EQUIP },
    423: { name: "Thermal Clip Storage", type: InventoryType.GEAR_EQUIP },
    424: { name: "Adaptive War Amp", type: InventoryType.GEAR_EQUIP },
    425: { name: "Engineering Kit", type: InventoryType.GEAR_EQUIP },
    426: { name: "Densified Ammunition", type: InventoryType.GEAR_EQUIP },
    // 427..433
    434: { name: 'AssaultRifleDamagePistolDamage_1', type: InventoryType.GEAR_EQUIP },
    435: { name: 'MeleeDamageBioticDamage_1', type: InventoryType.GEAR_EQUIP },
    436: { name: 'ShieldStrengthMeleeDamage_1', type: InventoryType.GEAR_EQUIP },
    437: { name: 'ShotgunDamageGrenadeCap_1', type: InventoryType.GEAR_EQUIP },
    438: { name: 'SniperDamageSMGDamage_1', type: InventoryType.GEAR_EQUIP },
    439: { name: 'TechDamagePowerCooldown_1', type: InventoryType.GEAR_EQUIP },
    440: { name: 'WeaponStabilityAmmoCapacity_1', type: InventoryType.GEAR_EQUIP },
    441: { name: 'AmmoCapacity_1', type: InventoryType.GEAR_EQUIP },
    442: { name: 'BioticDamage_1', type: InventoryType.GEAR_EQUIP },
    443: { name: 'TechDamage_1', type: InventoryType.GEAR_EQUIP },
    444: { name: 'WeaponDamage_All_1', type: InventoryType.GEAR_EQUIP },
    445: { name: 'AssaultRifleDamagePistolDamage_2', type: InventoryType.GEAR_EQUIP },
    446: { name: 'MeleeDamageBioticDamage_2', type: InventoryType.GEAR_EQUIP },
    447: { name: 'ShieldStrengthMeleeDamage_2', type: InventoryType.GEAR_EQUIP },
    448: { name: 'Combo_ShotgunDamageGrenadeCap_2', type: InventoryType.GEAR_EQUIP },
    449: { name: 'SniperDamageSMGDamage_2', type: InventoryType.GEAR_EQUIP },
    450: { name: 'TechDamagePowerCooldown_2', type: InventoryType.GEAR_EQUIP },
    451: { name: 'WeaponStabilityAmmoCapacity_2', type: InventoryType.GEAR_EQUIP },
    452: { name: 'Ammo Capacity Booster', type: InventoryType.CONSUMABLE_OTHER },
    453: { name: 'Biotic Damage Booster', type: InventoryType.CONSUMABLE_OTHER },
    454: { name: 'Tech Damage Booster', type: InventoryType.CONSUMABLE_OTHER },
    455: { name: 'Weapon Damage Booster', type: InventoryType.CONSUMABLE_OTHER },
    // 456..465
    466: { name: "AssaultRifleMelee", type: InventoryType.WEAPON_EQUIP },
    467: { name: "AssaultRifleSuperPen", type: InventoryType.WEAPON_EQUIP },
    468: { name: "N7 Typhoon", type: InventoryType.ASSAULT_RIFLE },
    469: { name: "N7 Piranha", type: InventoryType.SHOTGUN },
    470: { name: "Acolyte", type: InventoryType.HEAVY_PISTOL },
    // 471..479
    480: { name: "Turian Havoc Soldier", type: InventoryType.CHARACTER },
    481: { name: "Turian Ghost Infiltrator", type: InventoryType.CHARACTER },
    // 482..483
    484: { name: "Incendiary Rounds 4", type: InventoryType.AMMO_EQUIP },
    485: { name: "Disruptor Rounds 4", type: InventoryType.AMMO_EQUIP },
    486: { name: "Armor Piercing Rounds 4", type: InventoryType.AMMO_EQUIP },
    487: { name: "Warp Rounds 4", type: InventoryType.AMMO_EQUIP },
    488: { name: "Cryo Rounds 4", type: InventoryType.AMMO_EQUIP },
    489: { name: "Power Amplifier Module 4", type: InventoryType.ARMOR_EQUIP },
    490: { name: "Cyclonic Modulator 4", type: InventoryType.ARMOR_EQUIP },
    // 491..499
    500: { name: "Volus Adept", type: InventoryType.CHARACTER },
    501: { name: "Volus Engineer", type: InventoryType.CHARACTER },
    503: { name: "Turian Saboteur Engineer", type: InventoryType.CHARACTER },
    504: { name: "Drell Assassin Infiltrator", type: InventoryType.CHARACTER },
    505: { name: "Volus Mercenary Sentinel", type: InventoryType.CHARACTER },
    506: { name: "Geth Trooper Soldier", type: InventoryType.CHARACTER },
    507: { name: "Volus Protector Vanguard", type: InventoryType.CHARACTER },
    508: { name: "Batarian Slasher Adept", type: InventoryType.CHARACTER },
    509: { name: "Vorcha Hunter Engineer", type: InventoryType.CHARACTER },
    510: { name: "Asari Huntress Infiltrator", type: InventoryType.CHARACTER },
    511: { name: "Asari Valkyrie Sentinel", type: InventoryType.CHARACTER },
    512: { name: "Quarian Marksman Soldier", type: InventoryType.CHARACTER },
    513: { name: "Batarian Brawler Vanguard", type: InventoryType.CHARACTER },
    514: { name: "Krogan Shaman Adept", type: InventoryType.CHARACTER },
    515: { name: "Polonium Rounds 1 (unused)", type: InventoryType.AMMO_EQUIP },
    // 516
    517: { name: "Explosive Rounds 1", type: InventoryType.AMMO_EQUIP },
    518: { name: "Drill Rounds 1", type: InventoryType.AMMO_EQUIP },
    519: { name: "Phasic Rounds 1", type: InventoryType.AMMO_EQUIP },
    520: { name: "Polonium Rounds 2 (unused)", type: InventoryType.AMMO_EQUIP },
    // 521
    522: { name: "Explosive Rounds 2", type: InventoryType.AMMO_EQUIP },
    523: { name: "Drill Rounds 2", type: InventoryType.AMMO_EQUIP },
    524: { name: "Phasic Rounds 2", type: InventoryType.AMMO_EQUIP },
    525: { name: "Polonium Rounds 3 (unused)", type: InventoryType.AMMO_EQUIP },
    // 526
    527: { name: "Explosive Rounds 3", type: InventoryType.AMMO_EQUIP },
    528: { name: "Drill Rounds 3", type: InventoryType.AMMO_EQUIP },
    529: { name: "Phasic Rounds 3", type: InventoryType.AMMO_EQUIP },
    // 530..531
    532: { name: "Collector Sniper Rifle", type: InventoryType.SNIPER_RIFLE },
    533: { name: "Collector SMG", type: InventoryType.SUB_MACHINE_GUN },
    // 535
    536: { name: "Medi-Gel Transmitter", type: InventoryType.GEAR_EQUIP },
    537: { name: "Armored Compartments", type: InventoryType.GEAR_EQUIP },
    538: { name: "Responder Loadout", type: InventoryType.GEAR_EQUIP },
    539: { name: "Survivor Loadout", type: InventoryType.GEAR_EQUIP },
    540: { name: "Assault Loadout", type: InventoryType.GEAR_EQUIP },
    // 541..575
    576: { name: "Geth Juggernaut Soldier", type: InventoryType.CHARACTER },
    577: { name: "Awakened Collector Adept", type: InventoryType.CHARACTER },
    // 578..582
    583: { name: "Krogan Warlord Sentinel", type: InventoryType.CHARACTER },
    584: { name: "Talon Mercenary Engineer", type: InventoryType.CHARACTER },
    // 585..591
    592: { name: "Cabal Vanguard", type: InventoryType.CHARACTER },
    // 593..601
    602: { name: "Alliance Infiltration Unit Infiltrator", type: InventoryType.CHARACTER },
    603: { name: "Geth Scanner", type: InventoryType.GEAR_EQUIP },
    604: { name: "Batarian Gauntlet", type: InventoryType.GEAR_EQUIP },
    // 605..622
    623: { name: "M-7 Lancer", type: InventoryType.ASSAULT_RIFLE },
    624: { name: "Blood Pack Punisher", type: InventoryType.SUB_MACHINE_GUN },
    625: { name: "Venom Shotgun", type: InventoryType.SHOTGUN },
    626: { name: "Geth Spitfire", type: InventoryType.ASSAULT_RIFLE },
    627: { name: "Adas Anti-Synthetic Rifle", type: InventoryType.ASSAULT_RIFLE },
    628: { name: "Executioner Pistol", type: InventoryType.HEAVY_PISTOL },
    629: { name: "M-11 Suppressor", type: InventoryType.HEAVY_PISTOL },
    // 630..652
    653: { name: "Assault Rifle UltraLight", type: InventoryType.WEAPON_EQUIP },
    654: { name: "Sniper Rifle UltraLight", type: InventoryType.WEAPON_EQUIP },
    655: { name: "Shotgun Rifle UltraLight", type: InventoryType.WEAPON_EQUIP },
    656: { name: "Pistol Power Damage", type: InventoryType.WEAPON_EQUIP },
    657: { name: "SMG Power Damage", type: InventoryType.WEAPON_EQUIP },
    // 658..671
}
